<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Latihan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Latihan_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','latihan/tbl_latihan_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Latihan_model->json();
    }

    public function read($id) 
    {
        $row = $this->Latihan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'nama' => $row->nama,
		'file' => $row->file,
	    );
            $this->template->load('template','latihan/tbl_latihan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('latihan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('latihan/create_action'),
	    'id' => set_value('id'),
	    'nama' => set_value('nama'),
	    'file' => set_value('file'),
	);
        $this->template->load('template','latihan/tbl_latihan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();
        $file_upload = $this->upload_file();
        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
		'file' => $file_upload['file_name'],
	    );

            $this->Latihan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('latihan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Latihan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('latihan/update_action'),
		'id' => set_value('id', $row->id),
		'nama' => set_value('nama', $row->nama),
		'file' => set_value('file', $row->file),
	    );
            $this->template->load('template','latihan/tbl_latihan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('latihan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
		'file' => $this->input->post('file',TRUE),
	    );

            $this->Latihan_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('latihan'));
        }
    }
    function upload_file(){
        $config['upload_path']          = './assets/fotoku';
        $config['allowed_types']        = 'gif|jpg|png|pdf|word|txt';
        //$config['max_size']             = 100;
        //$config['max_width']            = 1024;
        //$config['max_height']           = 768;
        $this->load->library('upload', $config);
        $this->upload->do_upload('file');
        return $this->upload->data();
    }
    public function delete($id) 
    {
        $row = $this->Latihan_model->get_by_id($id);

        if ($row) {
            $this->Latihan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('latihan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('latihan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama', 'nama', 'trim|required');
	$this->form_validation->set_rules('file', 'file', 'trim');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

    public function word()
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=tbl_latihan.doc");

        $data = array(
            'tbl_latihan_data' => $this->Latihan_model->get_all(),
            'start' => 0
        );
        
        $this->load->view('latihan/tbl_latihan_doc',$data);
    }

}

/* End of file Latihan.php */
/* Location: ./application/controllers/Latihan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-01-24 04:26:57 */
/* http://harviacode.com */