<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Surat_lembur_model extends CI_Model
{

    public $table = 'tbl_surat_lembur';
    public $id = 'id_sl';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_sl,nomor,nama_pj,tgl_skpl,seksi,lembur_waktu,uraian_lembur,tgl_lembur,nama_pg1,nip_pg1,jabatan_pg1,nama_pg2,nip_pg2,jabatan_pg2,nama_pg3,nip_pg3,jabatan_pg3,nama_pg4,nip_pg4,jabatan_pg4,nama_pg5,nip_pg5,jabatan_pg5,jam_lembur1,jam_lembur2,bg_mengetahui,nama_mengetahui');
        $this->datatables->from('tbl_surat_lembur');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_surat_lembur.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('surat_lembur/pdf/$1'),'<i class="fa fa-print" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm target=>_blank'))." 
            ".anchor(site_url('surat_lembur/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('surat_lembur/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_sl');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_sl', $q);
	$this->db->or_like('nomor', $q);
	$this->db->or_like('nama_pj', $q);
	$this->db->or_like('tgl_skpl', $q);
	$this->db->or_like('seksi', $q);
	$this->db->or_like('lembur_waktu', $q);
	$this->db->or_like('uraian_lembur', $q);
	$this->db->or_like('tgl_lembur', $q);
	$this->db->or_like('nama_pg1', $q);
	$this->db->or_like('nip_pg1', $q);
	$this->db->or_like('jabatan_pg1', $q);
	$this->db->or_like('nama_pg2', $q);
	$this->db->or_like('nip_pg2', $q);
	$this->db->or_like('jabatan_pg2', $q);
	$this->db->or_like('nama_pg3', $q);
	$this->db->or_like('nip_pg3', $q);
	$this->db->or_like('jabatan_pg3', $q);
	$this->db->or_like('nama_pg4', $q);
	$this->db->or_like('nip_pg4', $q);
	$this->db->or_like('jabatan_pg4', $q);
	$this->db->or_like('nama_pg5', $q);
	$this->db->or_like('nip_pg5', $q);
	$this->db->or_like('jabatan_pg5', $q);
	$this->db->or_like('jam_lembur1', $q);
	$this->db->or_like('jam_lembur2', $q);
	$this->db->or_like('bg_mengetahui', $q);
	$this->db->or_like('nama_mengetahui', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_sl', $q);
	$this->db->or_like('nomor', $q);
	$this->db->or_like('nama_pj', $q);
	$this->db->or_like('tgl_skpl', $q);
	$this->db->or_like('seksi', $q);
	$this->db->or_like('lembur_waktu', $q);
	$this->db->or_like('uraian_lembur', $q);
	$this->db->or_like('tgl_lembur', $q);
	$this->db->or_like('nama_pg1', $q);
	$this->db->or_like('nip_pg1', $q);
	$this->db->or_like('jabatan_pg1', $q);
	$this->db->or_like('nama_pg2', $q);
	$this->db->or_like('nip_pg2', $q);
	$this->db->or_like('jabatan_pg2', $q);
	$this->db->or_like('nama_pg3', $q);
	$this->db->or_like('nip_pg3', $q);
	$this->db->or_like('jabatan_pg3', $q);
	$this->db->or_like('nama_pg4', $q);
	$this->db->or_like('nip_pg4', $q);
	$this->db->or_like('jabatan_pg4', $q);
	$this->db->or_like('nama_pg5', $q);
	$this->db->or_like('nip_pg5', $q);
	$this->db->or_like('jabatan_pg5', $q);
	$this->db->or_like('jam_lembur1', $q);
	$this->db->or_like('jam_lembur2', $q);
	$this->db->or_like('bg_mengetahui', $q);
	$this->db->or_like('nama_mengetahui', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Surat_lembur_model.php */
/* Location: ./application/models/Surat_lembur_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-24 17:00:07 */
/* Sugeng kurniawan*/