<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_pegawai_model extends CI_Model
{

    public $table = 'tbl_pegawai';
    public $id = 'id_pegawai';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_pegawai,nip,nama,jk,jab,pangkat,golongan,tmp_lahir,tgl_lahir,gol_darah,agama,status,telp,alamat');
        $this->datatables->from('tbl_pegawai');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_pegawai.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('pegawai/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('pegawai/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('pegawai/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_pegawai');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pegawai', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('jab', $q);
	$this->db->or_like('pangkat', $q);
	$this->db->or_like('golongan', $q);
	$this->db->or_like('tmp_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('gol_darah', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('telp', $q);
	$this->db->or_like('alamat', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pegawai', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('jab', $q);
	$this->db->or_like('pangkat', $q);
	$this->db->or_like('golongan', $q);
	$this->db->or_like('tmp_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('gol_darah', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('telp', $q);
	$this->db->or_like('alamat', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_pegawai_model.php */
/* Location: ./application/models/Tbl_pegawai_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-24 15:33:43 */
/* Sugeng kurniawan*/